version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: note_app
      POSTGRES_PASSWORD: "cgSS2jYlTq_HXvYTqZc4eF2zXBng5cXJ"
    volumes:
      - note_app_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "guJ7Wh1nr-ny73rrvoTQausU_nEUD3g3"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  note_app_data:
